#!/usr/bin/env python3
"""T-count survey: align PyZX-optimised circuits with their originals by windows.

The roadmap's working hypothesis (Rung 3) is that an optimiser's output relates
to its input by local rewrites that can be aligned as windows and checked by
``circuit_windows``. This script is the evidence run. For every circuit under
``benchmarks/survey/<name>/original.qasm`` and both PyZX pipelines of
``check_pyzx_benchmarks.py`` (``teleport`` = ``teleport_reduce`` +
``basic_optimization``; ``full_reduce`` = ``full_reduce`` + extraction +
``basic_optimization``) it

1. generates the optimised circuit and saves it as ``pyzx_<pipeline>.qasm``;
2. canonicalises both gate lists (a stable topological order under a
   commutation relation, so that reorderings of commuting gates disappear),
   diffs them with ``difflib.SequenceMatcher`` and turns the opcodes into
   windows ``(a, b)``;
3. replays the alignment in a Python model of the tactic (same
   ``Instr.CanCommute`` rules, same first-pullable-occurrence pull, windows
   fired as early as possible), refines it on failure (merge windows that are
   not equivalences on their own, absorb the gate that blocks a move) a
   bounded number of times, and orders the windows as they fire;
4. emits a Lean file with ``original``, ``optimized`` and
   ``theorem original_equiv_optimized : original ≡ᵤ optimized := by
   circuit_windows [...]`` and checks it with ``lake env lean`` under a
   timeout. Lean is the judge; the numpy unitaries used along the way are an
   untrusted oracle for diagnosis only.

Requires pyzx==0.9.0 and numpy. Results go to ``benchmarks/survey/results.json``;
``--table`` prints them as the Markdown table of ``benchmarks/survey/README.md``.
The circuits are generated by ``--generate`` (seeds recorded in the QASM
headers); the survey itself always reads the saved files.
"""

from __future__ import annotations

import argparse
import difflib
import heapq
import json
import os
import random
import re
import shutil
import signal
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pyzx as zx

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import check_pyzx_benchmarks as cpb  # noqa: E402

SURVEY = ROOT / "benchmarks" / "survey"
PIPELINES = ("teleport", "full_reduce")
DIAG = {"Z", "S", "Sdg", "T", "Tdg"}
QASM_NAMES = {"H": "h", "X": "x", "Y": "y", "Z": "z", "S": "s", "Sdg": "sdg", "T": "t",
              "Tdg": "tdg", "CX": "cx"}
CANONS = ("greedy/cancommute", "asap/cancommute", "greedy/strict", "asap/strict", "raw")

# Search bounds. A window's decide costs 2^k for k wires, so the search may
# find alignments wider than Lean can check within the timeout; both bounds
# are reported separately so a timeout is never confused with a missing
# alignment.
SEARCH_MAX_WIRES = 8
SEARCH_MAX_STEPS = 40
LEAN_MAX_WIRES = 4

Gate = tuple  # (name, wires): ("H", (3,)) or ("CX", (1, 3))


# --------------------------------------------------------------------------
# Gates, circuits, QASM
# --------------------------------------------------------------------------

def one(name: str, i: int) -> Gate:
    return (name, (i,))


def cx(c: int, t: int) -> Gate:
    return ("CX", (c, t))


def parse(instructions: list[str]) -> list[Gate]:
    """Parse ``check_pyzx_benchmarks.lean_instructions`` strings."""
    gates = []
    for s in instructions:
        name, *wires = s.split()
        gates.append((name, tuple(int(w) for w in wires)))
    return gates


def show(g: Gate) -> str:
    return " ".join([g[0], *map(str, g[1])])


def to_qasm(gates: list[Gate], n: int, header: list[str]) -> str:
    lines = ["OPENQASM 2.0;", 'include "qelib1.inc";'] + [f"// {h}" for h in header]
    lines.append(f"qreg q[{n}];")
    for name, w in gates:
        lines.append(f"{QASM_NAMES[name]} " + ",".join(f"q[{i}]" for i in w) + ";")
    return "\n".join(lines) + "\n"


def ccx(a: int, b: int, c: int) -> list[Gate]:
    """The seven-``T`` Toffoli of ``benchmarks/tof_3/README.md``."""
    return [one("H", c), cx(b, c), one("Tdg", c), cx(a, c), one("T", c), cx(b, c),
            one("Tdg", c), cx(a, c), one("T", b), one("T", c), one("H", c), cx(a, b),
            one("T", a), one("Tdg", b), cx(a, b)]


def ccz(a: int, b: int, c: int) -> list[Gate]:
    """The seven-``T`` doubly-controlled ``Z``: ``ccx`` without its Hadamards."""
    return [cx(b, c), one("Tdg", c), cx(a, c), one("T", c), cx(b, c), one("Tdg", c), cx(a, c),
            one("T", b), one("T", c), cx(a, b), one("T", a), one("Tdg", b), cx(a, b)]


def mod5_4() -> tuple[int, list[Gate]]:
    """``mod5_4`` as in the PyZX repository (``circuits/Fast/mod5_4_before``,
    Quipper ASCII, the NRSCM benchmark): ``X 4; H 4; CCZ 0 3 4; CCZ 2 3 4;
    H 4; CX 3 4; H 4; CCZ 1 2 4; H 4; CX 2 4; H 4; CCZ 0 1 4; H 4; CX 1 4;
    CX 0 4``, each ``CCZ`` in the seven-``T`` decomposition."""
    gates = [one("X", 4), one("H", 4)] + ccz(0, 3, 4) + ccz(2, 3, 4)
    gates += [one("H", 4), cx(3, 4), one("H", 4)] + ccz(1, 2, 4)
    gates += [one("H", 4), cx(2, 4), one("H", 4)] + ccz(0, 1, 4)
    gates += [one("H", 4), cx(1, 4), cx(0, 4)]
    return 5, gates


def tof(n: int) -> tuple[int, list[Gate]]:
    """``tof_n``: an ``n``-controlled NOT through ``n - 2`` clean ancillas.

    Controls ``0..n-1``, ancillas ``n..2n-3``, target ``2n-2``; the ancilla
    chain is computed, the target Toffoli applied, the chain uncomputed.
    """
    ctrl, anc, tgt = list(range(n)), list(range(n, 2 * n - 2)), 2 * n - 2
    chain = [(ctrl[0], ctrl[1], anc[0])] + [(anc[i - 1], ctrl[i + 1], anc[i])
                                            for i in range(1, n - 2)]
    toffolis = chain + [(anc[n - 3], ctrl[n - 1], tgt)] + chain[::-1]
    return 2 * n - 1, [g for t in toffolis for g in ccx(*t)]


def barenco_tof(n: int) -> tuple[int, list[Gate]]:
    """``barenco_tof_n``: Barenco et al. (1995) Lemma 7.2 with dirty ancillas.

    Same wire layout as ``tof``; ``4 (n - 2)`` Toffolis: a V-shaped chain from
    the target down to the first ancilla and back, then the chain again
    without its outermost Toffoli. Every ancilla is restored whatever its
    initial value.
    """
    ctrl, anc, tgt = list(range(n)), list(range(n, 2 * n - 2)), 2 * n - 2
    chain = [(ctrl[n - 1], anc[n - 3], tgt)]
    chain += [(ctrl[i + 1], anc[i - 1], anc[i]) for i in range(n - 3, 0, -1)]
    chain += [(ctrl[0], ctrl[1], anc[0])]
    toffolis = chain + chain[-2::-1] + chain[1:] + chain[-2:0:-1]
    return 2 * n - 1, [g for t in toffolis for g in ccx(*t)]


def cuccaro(n: int) -> tuple[int, list[Gate]]:
    """Cuccaro–Draper–Kutin–Moulton ripple-carry adder on ``n`` bits.

    Wires: carry-in ``0``, then ``b_i = 1 + 2i``, ``a_i = 2 + 2i``, carry-out
    ``2n + 1``. ``MAJ(c, b, a) = CX a b; CX a c; CCX c b a`` and
    ``UMA(c, b, a) = CCX c b a; CX a c; CX c b`` with the Toffoli of ``ccx``.
    """
    c, z = 0, 2 * n + 1
    b, a = [1 + 2 * i for i in range(n)], [2 + 2 * i for i in range(n)]

    def maj(c, b, a):
        return [cx(a, b), cx(a, c)] + ccx(c, b, a)

    def uma(c, b, a):
        return ccx(c, b, a) + [cx(a, c), cx(c, b)]

    gates = maj(c, b[0], a[0])
    for i in range(1, n):
        gates += maj(a[i - 1], b[i], a[i])
    gates += [cx(a[n - 1], z)]
    for i in range(n - 1, 0, -1):
        gates += uma(a[i - 1], b[i], a[i])
    gates += uma(c, b[0], a[0])
    return 2 * n + 2, gates


def random_circuit(qubits: int, depth: int, seed: int, p_had: float,
                   p_t: float) -> tuple[int, list[Gate]]:
    """``pyzx.generate.CNOT_HAD_PHASE_circuit`` with the global RNG seeded."""
    random.seed(seed)
    c = zx.generate.CNOT_HAD_PHASE_circuit(qubits, depth, p_had, p_t)
    return qubits, parse(cpb.lean_instructions(c))


def circuit_table() -> dict[str, tuple[list[str], int, list[Gate]]]:
    """Name -> (provenance header lines, qubits, gates)."""
    table = {}
    for n in (3, 4, 5):
        q, g = tof(n)
        table[f"tof_{n}"] = ([f"tof_{n}: {2 * n - 3} Toffolis (seven-T decomposition) computing "
                              f"an {n}-controlled NOT through {n - 2} clean ancillas",
                              "generated by scripts/tcount_survey.py --generate"], q, g)
    q, g = barenco_tof(3)
    table["barenco_tof_3"] = (["barenco_tof_3: Barenco et al. Lemma 7.2, four Toffolis "
                               "(seven-T decomposition), one dirty ancilla",
                               "generated by scripts/tcount_survey.py --generate"], q, g)
    q, g = mod5_4()
    table["mod5_4"] = (["mod5_4: transcribed from the PyZX repository, circuits/Fast/mod5_4_before "
                        "(Quipper ASCII; the NRSCM benchmark): X 4; H 4; CCZ 0 3 4; CCZ 2 3 4; "
                        "H 4; CX 3 4; H 4; CCZ 1 2 4; H 4; CX 2 4; H 4; CCZ 0 1 4; H 4; CX 1 4; "
                        "CX 0 4, each CCZ in the seven-T decomposition",
                        "generated by scripts/tcount_survey.py --generate"], q, g)
    for n in (2, 3, 4):
        q, g = cuccaro(n)
        table[f"cuccaro_{n}"] = ([f"cuccaro_{n}: Cuccaro ripple-carry adder on {n} bits, "
                                  "Toffoli-based MAJ/UMA (seven-T decomposition)",
                                  "generated by scripts/tcount_survey.py --generate"], q, g)
    for qubits, depth, seed in ((4, 30, 1), (5, 45, 2), (6, 60, 3)):
        p_had, p_t = 0.2, 0.3
        q, g = random_circuit(qubits, depth, seed, p_had, p_t)
        table[f"random_{qubits}q_d{depth}_s{seed}"] = (
            [f"pyzx {zx.__version__} generate.CNOT_HAD_PHASE_circuit(qubits={qubits}, "
             f"depth={depth}, p_had={p_had}, p_t={p_t}) after random.seed({seed}), "
             f"python {sys.version.split()[0]}",
             "generated by scripts/tcount_survey.py --generate"], q, g)
    return table


def generate(force: bool = False) -> None:
    """Write ``benchmarks/survey/<name>/original.qasm`` for every circuit."""
    for name, (header, n, gates) in circuit_table().items():
        d = SURVEY / name
        d.mkdir(parents=True, exist_ok=True)
        path = d / "original.qasm"
        if name == "tof_3":
            src = ROOT / "benchmarks" / "tof_3" / "original.qasm"
            if parse(cpb.lean_instructions(zx.Circuit.load(str(src)))) != gates:
                raise RuntimeError("tof(3) does not reproduce benchmarks/tof_3/original.qasm")
            if force or not path.exists():
                shutil.copy(src, path)
            continue
        text = to_qasm(gates, n, header)
        if path.exists() and not force:
            if path.read_text() != text:
                print(f"{name}: existing original.qasm differs from the generator; "
                      "use --force to overwrite", file=sys.stderr)
            continue
        path.write_text(text)
        loaded = zx.Circuit.load(str(path))
        if loaded.qubits != n or parse(cpb.lean_instructions(loaded)) != gates:
            raise RuntimeError(f"{name}: QASM round trip changed the circuit")
        print(f"{name}: {n} qubits, {len(gates)} gates, T-count {loaded.tcount()}")


# --------------------------------------------------------------------------
# Numeric oracle (untrusted; diagnosis only)
# --------------------------------------------------------------------------

_w8 = np.exp(1j * np.pi / 4)
MATS = {
    "H": np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2),
    "X": np.array([[0, 1], [1, 0]], dtype=complex),
    "Y": np.array([[0, -1j], [1j, 0]], dtype=complex),
    "Z": np.diag([1, -1]).astype(complex),
    "S": np.diag([1, 1j]).astype(complex),
    "Sdg": np.diag([1, -1j]).astype(complex),
    "T": np.diag([1, _w8]).astype(complex),
    "Tdg": np.diag([1, np.conj(_w8)]).astype(complex),
}


def _apply(state: np.ndarray, gate: Gate) -> np.ndarray:
    name, w = gate
    if name == "CX":
        c, t = w
        s = np.moveaxis(state, (c, t), (0, 1)).copy()
        s[1] = s[1][::-1].copy()
        return np.moveaxis(s, (0, 1), (c, t))
    s = np.moveaxis(state, w[0], 0)
    s = np.tensordot(MATS[name], s, axes=([1], [0]))
    return np.moveaxis(s, 0, w[0])


def unitary(gates: list[Gate], n: int) -> np.ndarray:
    u = np.eye(2 ** n, dtype=complex).reshape([2] * n + [2 ** n])
    for g in gates:
        u = _apply(u, g)
    return u.reshape(2 ** n, 2 ** n)


def compare(u: np.ndarray, v: np.ndarray) -> tuple[str, float | None]:
    """'exact', 'phase' (with the phase in units of pi) or 'different'."""
    if np.allclose(u, v, atol=1e-8):
        return "exact", None
    k = np.unravel_index(np.argmax(np.abs(u)), u.shape)
    ratio = v[k] / u[k]
    if abs(abs(ratio) - 1) < 1e-8 and np.allclose(u * ratio, v, atol=1e-8):
        return "phase", float(np.angle(ratio) / np.pi)
    return "different", None


def window_wires(left: list[Gate], right: list[Gate]) -> list[int]:
    """Wires in order of first appearance, as ``windowProof`` collects them."""
    wires: list[int] = []
    for _, w in left + right:
        for i in w:
            if i not in wires:
                wires.append(i)
    return wires


def window_valid(left: list[Gate], right: list[Gate]) -> bool:
    wires = window_wires(left, right)
    idx = {w: k for k, w in enumerate(wires)}
    ren = lambda gs: [(nm, tuple(idx[i] for i in w)) for nm, w in gs]  # noqa: E731
    k = len(wires)
    if k == 0:
        return True
    return compare(unitary(ren(left), k), unitary(ren(right), k))[0] == "exact"


# --------------------------------------------------------------------------
# Commutation, canonical orders, diff
# --------------------------------------------------------------------------

def can_commute(a: Gate, b: Gate) -> bool:
    """Mirror of ``Instr.CanCommute`` in ``CircuitEq/Rewriting.lean``."""
    if a == b:
        return True
    (g, wa), (h, wb) = a, b

    def one_cnot(g, i, c, t):
        return (i != c and i != t) or (c != t and ((i == c and g in DIAG) or (i == t and g == "X")))

    if g != "CX" and h != "CX":
        return wa[0] != wb[0] or (g in DIAG and h in DIAG)
    if g != "CX":
        return one_cnot(g, wa[0], wb[0], wb[1])
    if h != "CX":
        return one_cnot(h, wb[0], wa[0], wa[1])
    return wa[0] != wb[1] and wb[0] != wa[1]


def strict_commute(a: Gate, b: Gate) -> bool:
    """Disjoint wires (or identical gates) only."""
    return a == b or not set(a[1]) & set(b[1])


def _key(g: Gate):
    return (min(g[1]), g[0], g[1])


def canonical_order(gates: list[Gate], canon: str) -> list[int]:
    """A permutation (canonical position -> raw index) that is a linear
    extension of the dependency DAG under the chosen commutation relation.

    ``greedy`` emits the available gate with the smallest ``(min wire, name)``
    key first (a priority topological sort); ``asap`` sorts by longest-path
    layer, then key. ``raw`` keeps the list as it is.
    """
    if canon == "raw":
        return list(range(len(gates)))
    method, rel = canon.split("/")
    commute = can_commute if rel == "cancommute" else strict_commute
    n = len(gates)
    preds = [[i for i in range(j) if not commute(gates[i], gates[j])] for j in range(n)]
    if method == "asap":
        layer = [0] * n
        for j in range(n):
            layer[j] = max([layer[i] + 1 for i in preds[j]], default=0)
        return sorted(range(n), key=lambda k: (layer[k], _key(gates[k]), k))
    succs = [[] for _ in range(n)]
    indeg = [len(p) for p in preds]
    for j in range(n):
        for i in preds[j]:
            succs[i].append(j)
    heap = [(_key(gates[i]), i) for i in range(n) if indeg[i] == 0]
    heapq.heapify(heap)
    order = []
    while heap:
        _, i = heapq.heappop(heap)
        order.append(i)
        for j in succs[i]:
            indeg[j] -= 1
            if indeg[j] == 0:
                heapq.heappush(heap, (_key(gates[j]), j))
    return order


@dataclass
class Alignment:
    """Windows as index sets into the raw lists, plus the context matching."""
    xs: list[Gate]
    ys: list[Gate]
    windows: list[tuple[list[int], list[int]]]
    match: dict[int, int]  # context: raw xs index -> raw ys index
    canon: str
    log: list[str] = field(default_factory=list)

    def copy(self) -> "Alignment":
        return Alignment(self.xs, self.ys, [(list(a), list(b)) for a, b in self.windows],
                         dict(self.match), self.canon, list(self.log))

    def inverse(self) -> dict[int, int]:
        return {j: i for i, j in self.match.items()}

    def owner_x(self, i: int) -> int | None:
        return next((w for w, (a, _) in enumerate(self.windows) if i in a), None)

    def owner_y(self, j: int) -> int | None:
        return next((w for w, (_, b) in enumerate(self.windows) if j in b), None)

    def lists(self, w: int) -> tuple[list[Gate], list[Gate]]:
        a, b = self.windows[w]
        return [self.xs[i] for i in a], [self.ys[j] for j in b]

    def wires(self, w: int) -> list[int]:
        return window_wires(*self.lists(w))

    def size(self, w: int) -> int:
        a, b = self.windows[w]
        return len(a) + len(b)

    def absorb(self, w: int, i: int | None, j: int | None) -> None:
        """Move a context pair (or one side of it) into window ``w``."""
        a, b = self.windows[w]
        if i is not None:
            if i in self.match:
                jj = self.match.pop(i)
                if j is None:
                    j = jj
            if i not in a:
                a.append(i)
                a.sort()
        if j is not None and j not in b:
            b.append(j)
            b.sort()

    def merge(self, ws: list[int]) -> int:
        ws = sorted(set(ws))
        a = sorted({i for w in ws for i in self.windows[w][0]})
        b = sorted({j for w in ws for j in self.windows[w][1]})
        for w in reversed(ws):
            del self.windows[w]
        self.windows.append((a, b))
        return len(self.windows) - 1

    def new_window(self, i: int, j: int) -> int:
        assert self.match.get(i) == j
        del self.match[i]
        self.windows.append(([i], [j]))
        return len(self.windows) - 1

    def cost(self) -> int:
        """Estimated decide cost, gates times ``4^k`` summed over the windows."""
        return sum(self.size(w) * 4 ** len(self.wires(w)) for w in range(len(self.windows)))

    def stats(self) -> dict:
        if not self.windows:
            return {"windows": 0, "max_wires": 0, "max_gates": 0, "cost": 0}
        return {"windows": len(self.windows),
                "max_wires": max(len(self.wires(w)) for w in range(len(self.windows))),
                "max_gates": max(self.size(w) for w in range(len(self.windows))),
                "cost": self.cost()}

    def describe(self) -> list[str]:
        return [f"[{', '.join(map(show, l))}] <-> [{', '.join(map(show, r))}]"
                for l, r in (self.lists(w) for w in range(len(self.windows)))]


def initial_alignment(xs: list[Gate], ys: list[Gate], canon: str) -> Alignment:
    """Diff the canonical orders; opcodes become windows, equal runs context."""
    px, py = canonical_order(xs, canon), canonical_order(ys, canon)
    cx_, cy_ = [xs[i] for i in px], [ys[j] for j in py]
    sm = difflib.SequenceMatcher(None, cx_, cy_, autojunk=False)
    windows, match = [], {}
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            for k in range(i2 - i1):
                match[px[i1 + k]] = py[j1 + k]
        else:
            windows.append((sorted(px[i1:i2]), sorted(py[j1:j2])))
    return Alignment(xs, ys, windows, match, canon)


# --------------------------------------------------------------------------
# The tactic's replay, modelled
# --------------------------------------------------------------------------

Item = tuple[int, Gate]  # (raw index, gate)


def pull_one(g: Gate, xs: list[Item]):
    """First occurrence of ``g`` that commutes with everything before it.

    Returns ``(rest, index, None)`` or ``(None, None, (kind, blockers))`` with
    ``kind`` ``"blocked"`` (blockers of the first occurrence) or ``"absent"``.
    """
    first_blockers = None
    for k, (i, h) in enumerate(xs):
        if h == g:
            blockers = [xs[m] for m in range(k) if not can_commute(g, xs[m][1])]
            if not blockers:
                return xs[:k] + xs[k + 1:], i, None
            if first_blockers is None:
                first_blockers = blockers
    if first_blockers is None:
        return None, None, ("absent", [])
    return None, None, ("blocked", first_blockers)


def pull_many(gates: list[Gate], xs: list[Item]):
    """Pull ``gates`` in order; returns ``(rest, consumed, None)`` or
    ``(None, None, (position, gate, kind, blockers))``."""
    consumed = []
    for pos, g in enumerate(gates):
        xs, i, err = pull_one(g, xs)
        if err:
            return None, None, (pos, g, *err)
        consumed.append(i)
    return xs, consumed, None


@dataclass
class Replay:
    ok: bool
    fired: list[int]
    consumed_x: set[int]
    consumed_y: set[int]
    failure: dict | None = None


def replay(al: Alignment, dynamic: bool = True) -> Replay:
    """``alignWindows`` of ``CircuitEq/Tactic.lean``: at each step fire the
    pending window if both sides can be pulled to the front, else pull the next
    gate of ``ys`` from ``xs``. With ``dynamic`` every pending window is tried,
    which yields the order in which the tactic must be given them."""
    xs: list[Item] = list(enumerate(al.xs))
    ys: list[Item] = list(enumerate(al.ys))
    pending = list(range(len(al.windows)))
    fired: list[int] = []
    cons_x: set[int] = set()
    cons_y: set[int] = set()

    def fail(kind, **info):
        return Replay(False, fired, cons_x, cons_y,
                      {"kind": kind, "pending": list(pending), "xs": xs, "ys": ys, **info})

    while True:
        done = False
        for w in (pending if dynamic else pending[:1]):
            left, right = al.lists(w)
            xs2, cx2, err = pull_many(left, xs)
            if err:
                continue
            ys2, cy2, err = pull_many(right, ys)
            if err:
                continue
            xs, ys = xs2, ys2
            cons_x.update(cx2)
            cons_y.update(cy2)
            fired.append(w)
            pending.remove(w)
            done = True
            break
        if done:
            continue
        if not ys:
            if pending:
                return fail("not_placed", window=pending[0])
            if xs:
                return fail("unmatched_left", left=[i for i, _ in xs])
            return Replay(True, fired, cons_x, cons_y)
        (j, y) = ys[0]
        xs2, i, err = pull_one(y, xs)
        if err:
            return fail(err[0], y=(j, y), blockers=err[1])
        ys = ys[1:]
        xs = xs2
        cons_x.add(i)
        cons_y.add(j)


def diagnose_window(al: Alignment, w: int, xs: list[Item], ys: list[Item]) -> dict:
    """Why window ``w`` cannot fire on the remaining lists."""
    left, right = al.lists(w)
    _, _, err = pull_many(left, xs)
    if err:
        pos, g, kind, blockers = err
        return {"side": "left", "gate": g, "kind": kind, "blockers": blockers}
    _, _, err = pull_many(right, ys)
    if err:
        pos, g, kind, blockers = err
        return {"side": "right", "gate": g, "kind": kind, "blockers": blockers}
    return {"side": None, "kind": "pullable"}


# --------------------------------------------------------------------------
# Bounded refinement
# --------------------------------------------------------------------------

class GiveUp(Exception):
    pass


def _absorb_blockers(al: Alignment, w: int, side: str, blockers: list[Item],
                     consumed_x: set[int], consumed_y: set[int]) -> int:
    """Absorb the blocking gates (with their matches) into window ``w``,
    merging windows that own a blocker; returns the resulting window id."""
    inv = al.inverse()
    ws = [w]
    pairs = []
    for idx, _ in blockers:
        owner = al.owner_x(idx) if side == "left" else al.owner_y(idx)
        if owner is not None:
            ws.append(owner)
        elif side == "left":
            j = al.match.get(idx)
            if j is None or j in consumed_y:
                raise GiveUp("occurrence ambiguity: a blocking context gate's partner was "
                             "already consumed by an earlier pull of an equal gate")
            pairs.append((idx, j))
        else:
            i = inv.get(idx)
            if i is None or i in consumed_x:
                raise GiveUp("occurrence ambiguity: a blocking context gate's partner was "
                             "already consumed by an earlier pull of an equal gate")
            pairs.append((i, idx))
    w = al.merge(ws) if len(ws) > 1 else w
    for i, j in pairs:
        al.absorb(w, i, j)
    return w


def refine(al: Alignment, r: Replay) -> Alignment:
    """One refinement step from a replay failure; raises ``GiveUp``."""
    f = r.failure
    al = al.copy()
    inv = al.inverse()
    if f["kind"] in ("blocked", "absent"):
        j, y = f["y"]
        w = al.owner_y(j)
        if w is None:  # a context gate
            i = inv.get(j)
            if f["kind"] == "absent" or i is None:
                raise GiveUp(f"context gate {show(y)} has no pullable partner left: an earlier "
                             "pull consumed an equal gate (occurrence ambiguity)")
            owners = {al.owner_x(b) for b, _ in f["blockers"]} - {None}
            if owners:
                w = al.merge(sorted(owners))
                al.absorb(w, i, j)
                al.log.append(f"absorb {show(y)} into the window whose gates block it")
            else:
                w = al.new_window(i, j)
                al.log.append(f"new commutation window at {show(y)}")
            w = _absorb_blockers(al, w, "left", [b for b in f["blockers"]
                                                 if al.owner_x(b[0]) is None and b[0] != i],
                                 r.consumed_x, r.consumed_y)
        else:
            d = diagnose_window(al, w, f["xs"], f["ys"])
            if d["kind"] == "absent":
                raise GiveUp(f"window gate {show(d['gate'])} was consumed as context earlier "
                             "(occurrence ambiguity)")
            if d["kind"] == "pullable":
                raise GiveUp("window reported unplaceable but pullable (model inconsistency)")
            al.log.append(f"grow window by the gates blocking {show(d['gate'])} on its {d['side']}")
            _absorb_blockers(al, w, d["side"], d["blockers"], r.consumed_x, r.consumed_y)
    elif f["kind"] == "not_placed":
        w = f["window"]
        d = diagnose_window(al, w, f["xs"], f["ys"])
        if d["kind"] != "blocked":
            raise GiveUp(f"window could not be placed at the end ({d['kind']})")
        al.log.append(f"grow window by the gates blocking {show(d['gate'])} on its {d['side']}")
        _absorb_blockers(al, w, d["side"], d["blockers"], r.consumed_x, r.consumed_y)
    else:
        raise GiveUp("unmatched instructions on the left after the walk")
    return al


def _time(al: Alignment, w: int) -> int:
    """A raw-``xs`` coordinate for a window, for nearest-neighbour merging."""
    a, b = al.windows[w]
    if a:
        return min(a)
    inv = al.inverse()
    before = [inv[j] for j in range(min(b)) if j in inv]
    return max(before, default=-1) + 1


def rematch(al: Alignment) -> Alignment:
    """Pair identical gates of a pure deletion with a pure insertion as context.

    A single non-local move perturbs the canonical interleaving of nearby
    independent gates, and the diff then reports them deleted here and
    inserted there. Those are moves, not rewrites; the replay handles the
    licensed ones and the blocked ones become commutation windows."""
    al = al.copy()
    while True:
        best = None
        for u, (a, b) in enumerate(al.windows):
            if not a or b:
                continue
            for v, (a2, b2) in enumerate(al.windows):
                if a2 or not b2:
                    continue
                used, pairs = set(), []
                for i in a:
                    for j in b2:
                        if j not in used and al.xs[i] == al.ys[j]:
                            used.add(j)
                            pairs.append((i, j))
                            break
                if pairs and (best is None or len(pairs) > len(best[2])):
                    best = (u, v, pairs)
        if best is None:
            return al
        u, v, pairs = best
        for i, j in pairs:
            al.windows[u][0].remove(i)
            al.windows[v][1].remove(j)
            al.match[i] = j
        al.log.append(f"re-match {len(pairs)} moved gates ({show(al.xs[pairs[0][0]])}, …) as context")
        al.windows = [(a, b) for a, b in al.windows if a or b]


def violations(al: Alignment, w: int) -> set[tuple[int, int]]:
    """Context pairs window ``w`` cannot fire around, from the replay's rules.

    The window fires at the earliest step ``p`` at which its left gates can
    be pulled through the unconsumed context and its right gates through the
    context before the first of them. A context gate must join the window if
    it is unconsumed then and sits before a left gate it does not commute
    with, if it is consumed before then but sits behind such a left gate, or
    if it lies inside the right side's span before a right gate it does not
    commute with."""
    a, b = al.windows[w]
    first = min(b) if b else None
    p = 0
    for i, j in al.match.items():
        c = al.xs[i]
        if first is not None and j >= first:
            continue
        if any(i < x and not can_commute(c, al.xs[x]) for x in a) or \
                any(j < y and not can_commute(c, al.ys[y]) for y in b):
            p = max(p, j + 1)
    out = set()
    for i, j in al.match.items():
        c = al.xs[i]
        if first is not None and j >= first:
            if any(i < x and not can_commute(c, al.xs[x]) for x in a):
                out.add((i, j))
            if any(j < y and not can_commute(c, al.ys[y]) for y in b):
                out.add((i, j))
        elif j < p and any(i > x and not can_commute(c, al.xs[x]) for x in a):
            out.add((i, j))
    return out


def apply_constraints(al: Alignment, w: int) -> bool:
    """Absorb violating context into ``w`` until there is none; True if any."""
    grown = False
    while True:
        pairs = violations(al, w)
        if not pairs:
            return grown
        for i, j in pairs:
            al.absorb(w, i, j)
        grown = True
        if len(al.wires(w)) > SEARCH_MAX_WIRES:
            raise GiveUp(f"a window grew beyond {SEARCH_MAX_WIRES} wires while absorbing the "
                         f"context it must fire around: {al.describe()[w][:200]}")


def fix_invalid(al: Alignment, invalid: list[int]) -> Alignment:
    """Windows that are not equivalences on their own: merge the smallest
    subset of them that becomes one (bounded search), else grow the first by
    the nearest context gate that does not commute with it."""
    from itertools import combinations
    trials = 0
    for size in range(2, min(len(invalid), 4) + 1):
        best = None
        for subset in combinations(invalid, size):
            trials += 1
            if trials > 400:
                break
            trial = al.copy()
            w = trial.merge(list(subset))
            try:
                apply_constraints(trial, w)
            except GiveUp:
                continue
            if window_valid(*trial.lists(w)):
                key = (len(trial.wires(w)), trial.size(w))
                if best is None or key < best[0]:
                    best = (key, subset, trial)
        if best is not None:
            _, subset, trial = best
            trial.log.append("merge non-equivalent windows " +
                             " and ".join(str(w + 1) for w in subset))
            return trial
    al = al.copy()
    w = invalid[0]
    left, right = al.lists(w)
    t = _time(al, w)
    cands = sorted((abs(i - t), i) for i, j in al.match.items()
                   if any(not can_commute(al.xs[i], g) for g in left + right))
    if not cands:
        raise GiveUp(f"{len(invalid)} window(s) are not equivalences on their own, no merge of "
                     f"up to four of them is one within {SEARCH_MAX_WIRES} wires, and window "
                     f"{w + 1} ({len(al.wires(w))} wires, {al.size(w)} gates) has no "
                     "non-commuting context left to grow into")
    _, i = cands[0]
    al.log.append(f"grow non-equivalent window {w + 1} by context gate {show(al.xs[i])}")
    al.absorb(w, i, None)
    return al


def search(xs: list[Gate], ys: list[Gate], canon: str,
           do_rematch: bool = True) -> tuple[Alignment | None, dict]:
    """Refine from the diff until the model replays, or give up. Returns the
    aligned windows (in firing order) or ``None``, and a report."""
    al = initial_alignment(xs, ys, canon)
    report = {"canon": canon, "rematch": do_rematch, "initial": al.stats(), "steps": 0,
              "reason": None, "matched": len(al.match),
              "unmatched": [len(xs) - len(al.match), len(ys) - len(al.match)]}
    if do_rematch:
        al = rematch(al)
    report["rematched"] = al.stats()
    inv = al.inverse()
    ux = [g for i, g in enumerate(xs) if i not in al.match]
    uy = [g for j, g in enumerate(ys) if j not in inv]
    report["unmatched_phases"] = [sum(g[0] in DIAG for g in ux), sum(g[0] in DIAG for g in uy)]
    report["unmatched_other"] = [len(ux) - report["unmatched_phases"][0],
                                 len(uy) - report["unmatched_phases"][1]]
    try:
        for step in range(SEARCH_MAX_STEPS):
            report["steps"] = step
            report["last"] = al.stats()
            state = (sorted(tuple(a) + (-1,) + tuple(b) for a, b in al.windows),
                     sorted(al.match.items()))
            if step and state == report.get("_state"):
                raise GiveUp("refinement makes no progress: " +
                             (al.log[-1] if al.log else "no refinement applied"))
            report["_state"] = state
            if al.windows and max(len(al.wires(w)) for w in range(len(al.windows))) > SEARCH_MAX_WIRES:
                bad = [w + 1 for w in range(len(al.windows)) if not window_valid(*al.lists(w))]
                raise GiveUp(f"a window grew beyond {SEARCH_MAX_WIRES} wires "
                             f"({report['last']['max_wires']} wires, {report['last']['max_gates']} "
                             f"gates) while {'it is still not an equivalence' if bad else 'chasing the context it must fire around'}")
            grown = False
            for w in range(len(al.windows)):
                trial = al.copy()
                if apply_constraints(trial, w):
                    trial.log.append(f"absorb the context window {w + 1} must fire around")
                    al, grown = trial, True
                    break
            if grown:
                continue
            invalid = [w for w in range(len(al.windows)) if not window_valid(*al.lists(w))]
            if invalid:
                report["invalid"] = [al.describe()[w] for w in invalid]
                al = fix_invalid(al, invalid)
                continue
            r = replay(al)
            if r.ok:
                ordered = al.copy()
                ordered.windows = [al.windows[w] for w in r.fired]
                report["final"] = ordered.stats()
                report["log"] = al.log
                return ordered, report
            report["failure"] = {k: v for k, v in r.failure.items() if k not in ("xs", "ys")}
            al = refine(al, r)
        raise GiveUp(f"no replayable alignment within {SEARCH_MAX_STEPS} refinement steps")
    except GiveUp as e:
        report["reason"] = str(e)
        report["log"] = al.log
        report["last"] = al.stats()
        report["last_windows"] = al.describe()
        report["last_invalid"] = [w + 1 for w in range(len(al.windows))
                                  if not window_valid(*al.lists(w))]
    report.pop("_state", None)
    return None, report


def best_alignment(xs: list[Gate], ys: list[Gate]) -> tuple[Alignment | None, list[dict], str]:
    """Search under every canonicalisation, with and without re-matching, and
    keep the replayable alignment with the narrowest widest window and then
    the smallest estimated decide cost. Returns it (or ``None``), all the
    search reports, and the name of the winning search."""
    found, best, attempts, which = None, None, [], ""
    for canon in CANONS:
        for do_rematch in (True, False):
            al, report = search(xs, ys, canon, do_rematch)
            attempts.append(report)
            if al is not None:
                st = al.stats()
                key = (st["max_wires"], st["cost"], st["windows"])
                if best is None or key < best:
                    found, best = al, key
                    which = canon + ("" if do_rematch else " (no re-match)")
    return found, attempts, which


# --------------------------------------------------------------------------
# Lean
# --------------------------------------------------------------------------

def lean_list(gates: list[Gate], indent: int, width: int = 80) -> str:
    """Format ``[g₁, g₂, …]`` wrapped at ``width`` columns."""
    items = [show(g) for g in gates]
    if not items:
        return "[]"
    lines, cur = [], "[" + items[0]
    for it in items[1:]:
        if len(cur) + 2 + len(it) + 1 > width - indent:
            lines.append(cur + ",")
            cur = it
        else:
            cur += ", " + it
    lines.append(cur + "]")
    return ("\n" + " " * indent).join(lines)


def lean_windows(al: Alignment) -> str:
    parts = []
    for w in range(len(al.windows)):
        l, r = al.lists(w)
        parts.append(f"({lean_list(l, 8)},\n        {lean_list(r, 8)})")
    return "[" + ",\n      ".join(parts) + "]"


def lean_module(namespace: str, n: int, xs: list[Gate], ys: list[Gate], al: Alignment,
                header: str = "") -> str:
    return (f"{header}import CircuitEq.Tactic\n\nnamespace {namespace}\n\nopen Instr\n\n"
            f"def original : Circuit {n} :=\n  {lean_list(xs, 4)}\n\n"
            f"def optimized : Circuit {n} :=\n  {lean_list(ys, 4)}\n\n"
            f"theorem original_equiv_optimized : original ≡ᵤ optimized := by\n"
            f"  circuit_windows\n    {lean_windows(al)}\n\nend {namespace}\n")


def run_lean(path: Path, timeout: float) -> dict:
    """``lake env lean path`` with a hard timeout (the process group is killed)."""
    t0 = time.time()
    p = subprocess.Popen(["lake", "env", "lean", str(path)], cwd=ROOT, stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT, text=True, start_new_session=True)
    try:
        out, _ = p.communicate(timeout=timeout)
        timed_out = False
    except subprocess.TimeoutExpired:
        os.killpg(p.pid, signal.SIGKILL)
        out, _ = p.communicate()
        timed_out = True
    elapsed = time.time() - t0
    errors = re.findall(r"^.*?:\d+:\d+: error: (.*)$", out, re.M)
    return {"ok": p.returncode == 0 and not timed_out and not errors, "time": round(elapsed, 1),
            "timeout": timed_out, "errors": errors, "output": out[-4000:]}


def classify_lean_error(msg: str) -> str:
    if "is blocked by a gate" in msg:
        return "blocked move"
    if "does not occur" in msg:
        return "absent gate"
    if "could not be placed" in msg:
        return "window not placed"
    if "unmatched instructions" in msg:
        return "unmatched left"
    if "not an equivalence" in msg:
        return "window refuted"
    return "other"


# --------------------------------------------------------------------------
# The survey
# --------------------------------------------------------------------------

def survey_pair(name: str, pipeline: str, workdir: Path, timeout: float, no_lean: bool,
                lean_max_wires: int) -> dict:
    d = SURVEY / name
    original = zx.Circuit.load(str(d / "original.qasm"))
    optimized = cpb.optimize(original, pipeline)
    out = d / f"pyzx_{pipeline}.qasm"
    qasm = optimized.to_qasm()
    if out.exists() and out.read_text() != qasm:
        print(f"{name}/{pipeline}: PyZX output differs from the saved fixture; overwriting",
              file=sys.stderr)
    out.write_text(qasm)
    n = original.qubits
    rec = {"name": name, "pipeline": pipeline, "qubits": n,
           "pyzx_gates": [len(original.gates), len(optimized.gates)],
           "tcount": [original.tcount(), optimized.tcount()]}
    try:
        xs = parse(cpb.lean_instructions(original))
        ys = parse(cpb.lean_instructions(optimized))
    except ValueError as e:
        rec.update(aligned="no", reason=f"untranslatable PyZX output: {e}")
        return rec
    rec["lean_gates"] = [len(xs), len(ys)]
    kind, phase = compare(unitary(xs, n), unitary(ys, n)) if n <= 12 else ("unchecked", None)
    rec["numeric"] = kind if phase is None else f"phase {phase:.3f}*pi"
    rec["initial_windows"] = {c: initial_alignment(xs, ys, c).stats() for c in CANONS}
    found, rec["attempts"], rec["canon"] = best_alignment(xs, ys)
    if found is None:
        rec["aligned"] = "no"
        last = rec["attempts"][0]
        rec["reason"] = f"no alignment ({last['canon']}): {last['reason']}"
        rec["windows"] = last["last"]["windows"]
        rec["max_wires"] = last["last"]["max_wires"]
        rec["max_gates"] = last["last"]["max_gates"]
        if kind == "phase":
            rec["reason"] = f"equivalent only up to a global phase ({rec['numeric']}); " + rec["reason"]
        return rec
    st = found.stats()
    rec.update(windows=st["windows"], max_wires=st["max_wires"], max_gates=st["max_gates"],
               window_list=found.describe(), refinements=found.log)
    rec["whole_register"] = st["max_wires"] == n
    if rec["whole_register"]:
        rec["reason"] = (f"the only window found spans the whole register ({n} wires, "
                         f"{st['max_gates']} gates): a brute-force decide, not a window proof")
    if no_lean:
        rec["aligned"] = "model"
        return rec
    if st["max_wires"] > lean_max_wires:
        rec["aligned"] = "unchecked"
        rec["reason"] = (f"alignment found but its widest window has {st['max_wires']} wires "
                         f"({st['max_gates']} gates); not sent to Lean (bound {lean_max_wires} "
                         "wires, decide cost 2^k); " + rec.get("reason", ""))
        return rec
    ns = "Quantum.Circuit.Survey." + "".join(p.capitalize() for p in f"{name}_{pipeline}".split("_"))
    path = workdir / f"{name}_{pipeline}.lean"
    path.write_text(lean_module(ns, n, xs, ys, found))
    res = run_lean(path, timeout)
    rec["lean_time"] = res["time"]
    rec["lean_file"] = str(path)
    if res["ok"]:
        rec["aligned"] = "yes"
    elif res["timeout"]:
        rec["aligned"] = "timeout"
        rec["reason"] = f"Lean check exceeded {timeout:.0f} s (widest window {st['max_wires']} wires)"
    else:
        rec["aligned"] = "no"
        first = res["errors"][0] if res["errors"] else res["output"][-500:]
        rec["reason"] = f"Lean rejected the alignment ({classify_lean_error(first)}): {first[:300]}"
        rec["lean_output"] = res["output"]
    return rec


def markdown_table(records: list[dict]) -> str:
    rows = ["| Circuit | Pipeline | Qubits | Gates | T-count | Matched | Aligned | Windows | "
            "Widest window | Lean time | Notes |",
            "|---|---|---:|---:|---:|---:|---|---:|---|---:|---|"]
    for r in records:
        g = r.get("lean_gates", r["pyzx_gates"])
        widest = f"{r['max_wires']}w / {r['max_gates']}g" if r.get("windows") else "—"
        t = f"{r['lean_time']:.0f} s" if "lean_time" in r else "—"
        matched = "—"
        if r.get("attempts"):
            a = r["attempts"][0]
            matched = f"{a['matched']}/{g[0]}"
        aligned = r.get("aligned", "?")
        if r.get("whole_register"):
            aligned += " (whole register)"
        rows.append(f"| {r['name']} | {r['pipeline']} | {r['qubits']} | {g[0]} → {g[1]} | "
                    f"{r['tcount'][0]} → {r['tcount'][1]} | {matched} | {aligned} | "
                    f"{r.get('windows', 0)} | {widest} | {t} | {r.get('note', '')} |")
    return "\n".join(rows)


def self_test() -> None:
    """Sanity checks of the generators and the replay model."""
    if zx.__version__ != "0.9.0":
        raise RuntimeError(f"Expected PyZX 0.9.0, found {zx.__version__}")
    toffoli = np.eye(8, dtype=complex)
    toffoli[[6, 7]] = toffoli[[7, 6]]
    u = unitary(ccx(0, 1, 2), 3)
    # axis order: qubit 0 is the most significant bit of the row index
    assert compare(u, toffoli)[0] == "exact", "ccx is not a Toffoli"
    ccz_mat = np.diag([1, 1, 1, 1, 1, 1, 1, -1]).astype(complex)
    assert compare(unitary(ccz(0, 1, 2), 3), ccz_mat)[0] == "exact", "ccz is not a CCZ"
    q, g = cuccaro(2)
    u = unitary(g, q)
    for x in range(2 ** q):
        bits = [(x >> (q - 1 - i)) & 1 for i in range(q)]
        c, b0, a0, b1, a1, z = bits
        a, b = a0 + 2 * a1, b0 + 2 * b1
        s = a + b + c
        s0, s1, carry = s & 1, (s >> 1) & 1, (s >> 2) & 1
        want = [c, s0, a0, s1, a1, z ^ carry]
        y = sum(bit << (q - 1 - i) for i, bit in enumerate(want))
        assert abs(u[y, x] - 1) < 1e-9, "cuccaro(2) is not an adder"
    src = ROOT / "benchmarks" / "tof_3"
    xs = parse(cpb.lean_instructions(zx.Circuit.load(str(src / "original.qasm"))))
    ys = parse(cpb.lean_instructions(zx.Circuit.load(str(src / "pyzx.qasm"))))
    assert tof(3)[1] == xs
    hand = [([one("T", 0), one("T", 0)], [one("S", 0)]),
            ([one("H", 3), cx(1, 3)], [one("H", 3), cx(1, 3), one("H", 3), one("H", 3)]),
            ([one("H", 4), cx(2, 4)], [one("H", 4), cx(2, 4), one("H", 4), one("H", 4)]),
            ([one("Tdg", 2), cx(3, 2), one("H", 3), cx(1, 3)],
             [one("H", 3), cx(1, 3), one("H", 3), one("Tdg", 2), cx(3, 2), one("H", 3)])]
    al = Alignment(xs, ys, [], {}, "hand")
    al.lists = lambda w: hand[w]  # type: ignore[method-assign]
    al.windows = [([], [])] * 4
    r = replay(al, dynamic=False)
    assert r.ok and r.fired == [0, 1, 2, 3], "the Tof3 alignment does not replay"
    print("self-test passed")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--generate", action="store_true", help="write the original circuits")
    parser.add_argument("--force", action="store_true", help="overwrite existing originals")
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--table", action="store_true", help="print results.json as Markdown")
    parser.add_argument("--circuits", nargs="*", help="subset of circuit names")
    parser.add_argument("--pipelines", nargs="*", default=list(PIPELINES), choices=PIPELINES)
    parser.add_argument("--timeout", type=float, default=600, help="Lean seconds per pair")
    parser.add_argument("--lean-max-wires", type=int, default=LEAN_MAX_WIRES)
    parser.add_argument("--no-lean", action="store_true", help="model only, no Lean runs")
    parser.add_argument("--workdir", type=Path, default=Path(os.environ.get(
        "TCOUNT_SURVEY_WORKDIR", "/tmp/tcount_survey")))
    parser.add_argument("--results", type=Path, default=SURVEY / "results.json")
    parser.add_argument("--emit", nargs=2, metavar=("NAME", "PIPELINE"),
                        help="print the Lean module of one aligned pair")
    args = parser.parse_args()
    if zx.__version__ != "0.9.0":
        raise RuntimeError(f"Expected PyZX 0.9.0, found {zx.__version__}")
    if args.self_test:
        self_test()
        return
    if args.generate:
        generate(args.force)
        return
    if args.table:
        print(markdown_table(json.loads(args.results.read_text())))
        return
    args.workdir.mkdir(parents=True, exist_ok=True)
    names = args.circuits or sorted(p.name for p in SURVEY.iterdir()
                                    if (p / "original.qasm").exists())
    if args.emit:
        name, pipeline = args.emit
        original = zx.Circuit.load(str(SURVEY / name / "original.qasm"))
        xs = parse(cpb.lean_instructions(original))
        ys = parse(cpb.lean_instructions(cpb.optimize(original, pipeline)))
        found, _, _ = best_alignment(xs, ys)
        if found is None:
            raise SystemExit("no alignment found")
        print(lean_module("Quantum.Circuit.Benchmarks.X", original.qubits, xs, ys, found))
        return
    records = []
    if args.results.exists():
        records = [r for r in json.loads(args.results.read_text())
                   if not (r["name"] in names and r["pipeline"] in args.pipelines)]
    for name in names:
        for pipeline in args.pipelines:
            t0 = time.time()
            rec = survey_pair(name, pipeline, args.workdir, args.timeout, args.no_lean,
                              args.lean_max_wires)
            rec["wall_time"] = round(time.time() - t0, 1)
            records.append(rec)
            print(f"{name}/{pipeline}: {rec.get('aligned')} windows={rec.get('windows')} "
                  f"widest={rec.get('max_wires')}w/{rec.get('max_gates')}g "
                  f"lean={rec.get('lean_time', '-')}s {rec.get('reason', '')}", flush=True)
            records.sort(key=lambda r: (names.index(r["name"]) if r["name"] in names else -1,
                                        PIPELINES.index(r["pipeline"])))
            args.results.write_text(json.dumps(records, indent=1, default=str) + "\n")


if __name__ == "__main__":
    main()
